// Auto-generated by LibreLane
module pll_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input sys_clk,
  input rst_n,
  input ref_clk,
  input[31:0] div_val,
  input[31:0] initial_freq,
  output pll_out,
  output lock_detect,
  output[31:0] debug_dco_word
);
endmodule
